fix(infra): add caddy container and update github actions
skkuding/codedang-monitor pull request #10
Opened 2024-01-21 09:23 UTC by ssupecial

Close #9 

docker-compose.yml 에 caddy container를 추가하였습니다.
이에 따라 github actions를 수정하였습니다. 
컨테이너들이 실행 중인지 확인하는 단계와 Caddyfile에 변경사항이 있을 때 reload하는 단계를 추가하였습니다.

docker-compose.yml 파일과 Caddyfile의 위치를 grafana 폴더가 아닌 레포지토리의 루트 폴더로 변경하였습니다.
이에 따라 파일 경로 수정이 필요한 경우 수정하였습니다.

2024-01-21 10:42 UTC, k1g99 commented on .github/workflows/update-stage.yml
> +      with:
여기서 sparse-checkout으로 `docker-compose.yml` 파일이랑 `Caddyfile`만 가져와버리면, `grafana/` 디렉토리 내부에 있는 파일들은 반영이 안되지 않을 것 같아요!

(뒤에 docker compose 에서 loki랑 grafana 실행될 때, 가져올 파일들이 없어서 오류가 나지 않을까 예상해봅니다...)

2024-01-21 10:42 UTC, k1g99 commented on .github/workflows/update-stage.yml
> +        docker compose --profile deploy up grafana -d --no-deps
`--no-dep`의 경우에는 `depends_on` 명령어처럼 의존관계가 있는 경우에 연결된 서비스를 실행을 제한하는 명령어입니다! 
아직까지 우리의 도커컴포즈 파일에는 컨테이너간의 의존관계가 없기 때문에 지워도 될 것 같아요!

2024-01-21 10:42 UTC, k1g99 commented on docker-compose.yml
> +    profiles: ['deploy']
Docker에서 `profiles` 옵션은 여러 서비스들 중에서 필요한 서비스들을 그룹화(?) 하기 위해서 사용할 수 있는 옵션입니다! 그런데 `deploy` 로 설정하는 것은 불필요한 작업인 것 같습니다! 

오히려 profile을 (caddy)와 (loki+grafana) 이렇게 나눌 수 있도록 설정하고, 컨테이너가 실행되고있는지 여부에 따라서
`- name: Initialize containers` 에서는 (caddy)와 (loki+grafana)를 모두 실행하고,
`- name: Run Docker Compose` 에서는 (loki+grafana)를 실행하는 방식으로 코드가 구성되면 어떨까요? 


profiles 참고 - https://docs.docker.com/compose/profiles/

2024-01-21 10:42 UTC, k1g99 commented on .github/workflows/update-stage.yml
> +        docker compose --profile deploy up -d --no-recreate
`docker-compose.yml` 파일에 관련된 커멘트 달아놨어요!

2024-01-21 11:04 UTC, ssupecial commented on .github/workflows/update-stage.yml
> +        docker compose --profile deploy up -d --no-recreate
오우 너무 단순하게 참고했네요..
자세히 코멘트 달아주셔서 감사합니다 ㅎㅎ
수정해서 다시 push 하겠습니다!

2024-01-22 01:39 UTC, ssupecial commented on .github/workflows/update-stage.yml
> +        docker compose --profile deploy up -d --no-recreate
수정해서 다시 푸쉬했는데 알림이 갔나요?
다시 확인해주세요!

2024-01-22 02:15 UTC, k1g99 requested changes
오타만 고치고 머지하면 될 것 같아요!!

2024-01-22 02:15 UTC, k1g99 commented on .github/workflows/update-stage.yml
> +        dockder compose --profile log up -d --no-recreate
`dockder` 오타!!!

2024-01-22 05:04 UTC, ssupecial commented on .github/workflows/update-stage.yml
> +        dockder compose --profile log up -d --no-recreate
오웁 죄송해요

2024-01-22 05:05 UTC, ssupecial commented on .github/workflows/update-stage.yml
> +        dockder compose --profile log up -d --no-recreate
수정했어요!

2024-01-22 06:00 UTC, k1g99 approved these changes
아푸룹!

2024-01-22 06:01 UTC, merged